### ISSUE TITLE
CodeSystem $lookup operation

### ISSUE THREAD

**Issue by azriel-healthpoint** [FlixCoder/fhir-sdk#23]
Hi there,

I'm trying out this SDK, and couldn't figure out if it's possible to call the [/CodeSystem/$lookup](https://www.hl7.org/fhir/codesystem-operation-lookup.html) operation:

```bash
GET $base_url/CodeSystem/$lookup?system=..&code=..
```

Would the SDK need to be extended to include methods like [`Client::operation_encounter_everything`](https://docs.rs/fhir-sdk/latest/fhir_sdk/client/struct.Client.html#method.operation_encounter_everything), or is there some way to invoke arbitrary operations through `Client` and [`OperationDefinition`](https://docs.rs/fhir-sdk/latest/fhir_sdk/r5/resources/struct.OperationDefinition.html)?

**Comment by FlixCoder** [comment]
Hi, thank you for the interest.

There is currently no generic way for arbitrary operations, partly due to unknown return types, partly due to the reason I want to implement proper more usable methods.

So if the operation is defined in the FHIR spec, it would just need additional methods for the operation. Otherwise it would need some kind of generic method.

**Comment by FlixCoder** [comment]
As of 0.14.0 it is now possible to send custom requests and therefore implement your own operations and implementing missing operations :)

```rust
let base = client.base_url();
let response = client.send_custom_request(|http| http.get(&format!("{base}/CodeSystem/$lookup")).query(...)).await?;
if response.status().is_success() {
    let parameters: Parameters = response.json().await?;
    // Do whatever with it.
}
```

**Comment by azriel-healthpoint** [comment]
Thank you 🙇!
